# From https://github.com/robbyrussell/oh-my-zsh
# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# see screenshoots at: https://github.com/robbyrussell/oh-my-zsh/wiki/themes
ZSH_THEME="awesomepanda"

# Set to this to use case-sensitive completion
CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git rails ruby macports rails3 svn textmate github heroku)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...

# CODE 
CODE=$HOME/Code

# ANDROIDSDK 
ANDROIDSDK=$CODE/android-sdk-mac_x86

# RAILS, RVM and MySQl http://erictarn.com/post/8225729243/how-i-installed-mysql-rvm-ruby-and-rails-on-lion
export CC=/usr/bin/gcc-4.2
export DYLD_LIBRARY_PATH="/usr/local/mysql/lib:$DYLD_LIBRARY_PATH"

# PATH
export PATH=/usr/local/bin:/opt/local/bin:/opt/local/sbin:/usr/local/mysql/bin:$ANDROIDSDK/tools/:$ANDROIDSDK/platform-tools/:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin:/usr/texbin

# FIX LOCALE
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# RVM
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # This loads RVM into a shell session.
